import {StyleSheet, Dimensions} from 'react-native';

const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

const styles = StyleSheet.create({
  messageDisplayer: {
    height: '85%',
  },
  message: {
    color: '#FFFFFF',
  },
  sendMessage: {
    position: 'absolute',
    bottom: 5,
    right: 0,
    width: '10%',
    height: '10%',
    padding: 1,
    margin: 1,
    marginRight: '3%',
    backgroundColor: 'transparent',
    elevation: 99,
  },
  inputMessage: {
    width: '80%',
    height: '10%',
    margin: 1,
    borderWidth: 2,
    borderColor: 'white',
    position: 'absolute',
    bottom: 5,
    left: 2,
    color: 'white',
    paddingHorizontal: 15,
  },
  boxChat: {
    position: 'absolute',
    bottom: '30%',
    right: 0,
    height: '70%',
    width: '70%',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  scollView: {
    width: '100%',
    height: '100%',
    zIndex: -3,
    elevation: -3,
  },
  container: {
    width: '100%',
    height: '100%',
    backgroundColor: '#1D1F20',
    elevation: -1,
    zIndex: -1,
  },
  welcomeBlock: {
    alignItems: 'center',
    marginTop: 120,
    marginBottom: 40,
    paddingHorizontal: 20,
  },
  welcomeTitle: {
    fontSize: 30,
    fontWeight: '700',
    color: '#e8eaed',
    letterSpacing: 0.3,
  },
  welcomeSubtitle: {
    fontSize: 14,
    color: '#c0cad5',
    marginTop: 6,
    letterSpacing: 0.2,
  },
  apiRtcLogo: {
    width: 160,
    height: 48,
    marginTop: 16,
  },
  cnxBadgeOuter: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    marginBottom: 24,
  },
  cnxBadge: {
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 20,
    padding: 8,
    marginRight: 8,
    elevation: 0,
  },
  cnxDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
  },
  cnxLabel: {
    fontSize: 14,
    color: '#c8d0da',
    fontWeight: '500',
    paddingRight: 6,
  },
  versionText: {
    position: 'absolute',
    bottom: 20,
    left: 0,
    right: 0,
    textAlign: 'center',
    fontSize: 12,
    color: '#8898a8',
  },
  remoteView: {
    width: windowWidth / 2 - 10,
    height: windowHeight / 4 - 10,
  },
  remoteViewHalf: {
    width: windowWidth,
    height: windowHeight / 2,
  },
  remoteViewGrid: {
    width: windowWidth / 2,
    height: windowHeight / 2,
  },
  input: {
    width: '60%',
    borderWidth: 1,
    marginBottom: 5,
    marginLeft: 10,
  },
  joinRow: {
    flexDirection: 'row',
    marginHorizontal: 20,
    marginTop: 16,
  },
  joinInput: {
    flex: 1,
    height: 50,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.18)',
    borderTopLeftRadius: 12,
    borderBottomLeftRadius: 12,
    borderRightWidth: 0,
    paddingHorizontal: 14,
    fontSize: 15,
    backgroundColor: 'rgba(255,255,255,0.07)',
    color: '#e8eaed',
  },
  joinBtn: {
    height: 50,
    paddingHorizontal: 22,
    backgroundColor: '#0080FF',
    borderTopRightRadius: 12,
    borderBottomRightRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  joinBtnText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 16,
  },
  main: {
    width: '100%',
    height: '100%',
    zIndex: -1,
    elevation: -1,
    position: 'absolute',
    top: 0,
    left: 0,
  },
  selfViewLocal: {
    position: 'absolute',
    width: 90,
    height: 130,
    bottom: 80,
    right: 10,
    backgroundColor: '#1a1a1a',
    elevation: 99,
    zIndex: 99,
    borderRadius: 10,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.35)',
  },
  selfScreenView: {
    position: 'absolute',
    width: 90,
    height: 130,
    bottom: 80,
    right: 110,
    backgroundColor: '#1a1a1a',
    elevation: 99,
    zIndex: 99,
    borderRadius: 10,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.35)',
  },
  selfScreenViewImg: {
    position: 'absolute',
    width: 90,
    height: 130,
    bottom: 80,
    right: 110,
    backgroundColor: '#1a1a1a',
    borderRadius: 10,
    overflow: 'hidden',
  },
  chatButton: {
    position: 'absolute',
    bottom: '5%',
    right: 10,
    width: 50,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 5,
    borderRadius: 100,
    backgroundColor: 'transparent',
    elevation: 99,
  },
  remoteContainer: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    top: 0,
    left: 0,
    zIndex: -1,
    backgroundColor: '#000',
  },
  remoteContainerFlex: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    backgroundColor: '#000',
  },
  renderButton: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    width: '100%',
    height: '10%',
    //backgroundColor: '#ededed',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  renderButtonComponent: {
    marginLeft: 2,
    marginRight: 2,
    borderRadius: 20,
    width: 50,
    height: 50,
    backgroundColor: '#8eabc7',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  svgButton: {
    width: '60%',
    height: '60%',
  },
  renderButtonText: {
    margin: 0,
  },
  renderButtonSwitch: {
    margin: 0,
  },
  screenCaptureInformation: {
    elevation: 20,
    position: 'absolute',
    width: '100%',
    height: '10%',
    bottom: '20%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  screenCaptureContainer: {
    width: '70%',
    height: '100%',
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'center',
    flexDirection: 'row',
    borderWidth: 2,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
  },
  screenCaptureButton: {
    backgroundColor: '#0084ff',
    borderWidth: 1,
    borderRadius: 5,
    padding: 10,
  },
  dialogContainer: {
    width: '50%',
    height: '100%',
    position: 'absolute',
    bottom: '7%',
    left: '6%',
  },
  dialogBox: {
    position: 'absolute',
    bottom: '3%',
    width: '100%',
    borderWidth: 1,
    borderColor: '#313335',
    borderRadius: 15,
    backgroundColor: '#1D1F20',
  },
  touchDialog: {
    //position: relative;
    width: '100%',
    height: 30,
    marginBottom: 4,
    marginTop: 4,
  },
  contentDialogCountainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginLeft: 20,
  },
  testDialog: {
    marginLeft: 20,
  },
  svgDialog: {
    height: '100%',
    width: 20,
  },
  menuRemoteContainer: {
    width: '50%',
    borderWidth: 1,
    borderColor: '#313335',
    borderRadius: 15,
    backgroundColor: '#1D1F20',
  },
  behindMenuRemoteContainer: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
    top: 0,
    left: 0,
    zIndex: 21,
    backgroundColor: 'rgba(0,0,0,0.5)',
  },

  /*VIDEO EFFECT PANEL — chevron + background selector*/
  ctrlGroup: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  ctrlGroupVideoBtn: {
    marginRight: 0,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
  },
  chevronBtn: {
    width: 18,
    height: 50,
    backgroundColor: '#5a7a97',
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    borderTopLeftRadius: 0,
    borderBottomLeftRadius: 0,
    marginLeft: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  chevronBtnOpen: {
    backgroundColor: '#4f9ef8',
  },
  videoEffectPanel: {
    position: 'absolute',
    bottom: '11%',
    left: '5%',
    width: 260,
    backgroundColor: '#292a2d',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 14,
    padding: 12,
    elevation: 100,
    zIndex: 100,
  },
  panelTitle: {
    color: '#e8eaed',
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 10,
  },
  bgOptionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  bgOption: {
    width: 72,
    height: 60,
    borderRadius: 8,
    backgroundColor: '#3c4043',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  bgOptionActive: {
    borderColor: '#4f9ef8',
  },
  bgOptionLabel: {
    color: '#e8eaed',
    fontSize: 11,
    marginTop: 2,
    textAlign: 'center',
  },
  bgOptionLabelOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    marginTop: 0,
    paddingVertical: 2,
    backgroundColor: 'rgba(0,0,0,0.55)',
    textAlign: 'center',
  },
  bgOptionNoneText: {
    color: '#9aa0a6',
    fontSize: 16,
  },
  bgApplyingText: {
    color: '#9aa0a6',
    fontSize: 11,
    marginTop: 8,
    textAlign: 'center',
  },
  panelOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 90,
  },

  /*PANSELFVIEW*/
  selfView: (x, y) => {
    return {
      width: '30%',
      height: '30%',
      zIndex: 20,
      position: 'absolute',
      transform: [{translateX: x}, {translateY: y}],
    };
  },
});

export {styles};
